& "./scripts/mesh-test-all.ps1"
& "./scripts/transform-test-all.ps1"
& "./scripts/pipeline-test-all.ps1"
& "./scripts/texture-test-all.ps1"
& "./scripts/sampler-test-all.ps1"
& "./scripts/material-test-all.ps1"
& "./scripts/entity-test-all.ps1"
& "./scripts/renderer-test-all.ps1"